import argparse, sys


class syslogLog:
    #TODO: Convert msg_text to string instead of list
    def __init__(self, time, device_id, msg_num, msg_text):
        self.time = time
        self.device_id = device_id
        self.msg_num = msg_num
        self.msg_text = msg_text
        # Account for rsyslog variants that include PID after process name
        self.process = self.msg_num.split("[")[0]

    def __str__(self):
        return "{} {} {} {}".format(self.time, self.device_id, self.msg_num, self.msg_text)

# Parser setup
parser = argparse.ArgumentParser(
    description="Analyze Linux Logs")
parser.add_argument(
    'file', 
    help='File to be passed as input')
parser.add_argument(
    '-m',
    '--message',
    help='Return logs with MESSAGE in the log message',)
parser.add_argument(
    '-p',
    '--process',
    help='Return logs generated by PROCESS, if any',)
parser.add_argument(
    '-s',
    '--summary',
    help='Report file summary information',
    action='store_true',)

args = parser.parse_args()

try:
    with open(args.file, 'r') as log:
        all_lines = log.readlines()
except FileNotFoundError:
    print("File not found or does not exist")
    sys.exit(-1)

# Parse raw lines into syslogLog objects and place into list
log_list = []
for line in all_lines:
    split_line = line.split()
    # TODO: Change parsing method to regex
    log = syslogLog(" ".join(split_line[:3]),
                    split_line[3],
                    split_line[4],
                    " ".join(split_line[5:]))

    log_list.append(log)


# -s, --summary
if(args.summary):
    applications = []
    for x in log_list:
        if ( not x.process in applications):
            applications.append(x.process) 

    print("Log timeline: {} <-> {}".format(log_list[0].time, log_list[-1].time))
    print("Line count: {}".format(len(log_list)))
    print("Applications: ")
    for x in sorted(applications):
        print("- {}".format(x))

# -m, --message
if(args.message):
    for x in log_list:
        if (args.message.lower() in x.msg_text.lower()) or (args.message.lower() in x.msg_num.lower()):
            print(x)

# -p, --process
if(args.process):
    for x in log_list:
        if args.process.lower() in x.msg_num.lower():
            print(x)


#TODO: Implement time search by range 